name: Actions test for tf-torch gcp deployment

on:
  release:
    types: [published]

jobs:

  deploy-to-vertex-ai-endpoint:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: consult-403720
      REGION: europe-west1
      IMAGE_NAME: tf-torch
      IMAGE_TAG: ${{ github.sha }}
      ENDPOINT_NAME: tf-torch
      MODEL_NAME: tf-torch
      
    steps:
      # Copies repo code to workspace
      - name: Check out repository code
        uses: actions/checkout@v3
      # Authenticates google cloud
      - name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          service_account: "for-vertex@consult-403720.iam.gserviceaccount.com"
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`
      # This step allows me to then run gsutil commands
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      
      # downloads model file to workspace
      - name: Download model
        run: |
          gsutil -m cp -r gs://fine-tuning-test-bucket/models/tf_model.keras ./models
          gsutil -m cp -r gs://fine-tuning-test-bucket/models/torch_model.pth ./models
          
      - name: Build and push docker container to GCR
        run: |
          gcloud auth configure-docker
          docker build -t "gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG" .
          docker push "gcr.io/$PROJECT_ID/$IMAGE_NAME:$IMAGE_TAG"
      
